<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows</TargetFramework>

		<AssemblyName>CamStudio</AssemblyName>
		<RootNamespace>CamStudio</RootNamespace>

		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>

		<PlatformTarget>x64</PlatformTarget>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>

	<ItemGroup>
		<ApplicationDefinition Include="src\App.xaml" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="FFmpeg.AutoGen.Abstractions" Version="9.0.1.1" />
		<PackageReference Include="FFmpeg.AutoGen.Bindings.DynamicallyLoaded" Version="9.0.1.1" />
	</ItemGroup>

	<ItemGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
		<None Include="ffmpeg\windows\arch-x64\bin\*.dll" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>



	<ItemGroup>
	  <None Remove="Native\windows\win10\dist\Release\CamStudioVirtualCamera.dll" />
	  <None Remove="Native\windows\win11\CamStudioVirtualCameraW11\x64\Release\CamStudioVirtualCameraW11.dll" />
	</ItemGroup>

	<!--<ItemGroup Condition="$([MSBuild]::IsOSPlatform('Linux'))">
		<None Include="ffmpeg\linux\arch-x64\lib\*.so*"
			  CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup> -->

	<!-- Win10 -->
	<ItemGroup>
		<None Include="Native\windows\win10\CamStudioVirtualCamera.sln" />
		<None Include="Native\windows\win10\dist\$(Configuration)\CamStudioVirtualCamera.dll" Link="CamStudioVirtualCamera.dll" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>
	<ItemGroup>
	  <None Remove="Native\windows\win10\dist\Release\CamStudioVirtualCamera.dll" />
	  <None Remove="Native\windows\win11\CamStudioVirtualCameraW11\x64\Release\CamStudioVirtualCameraW11.dll" />
	</ItemGroup>
	<ItemGroup>
		<None Include="Native\windows\win10\dist\$(Configuration)\CamStudioVirtualCamera.dll" Link="CamStudioVirtualCamera.dll" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>


	<!-- Win11 -->
	<ItemGroup>
		<None Include="Native\windows\win11\CamStudioVirtualCameraW11\x64\$(Configuration)\CamStudioVirtualCameraW11.dll" Link="CamStudioVirtualCameraW11.dll" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Native\windows\win10\dist\Release\" />
	</ItemGroup>

</Project>